DELETE FROM TA_USERS WHERE 1 = 1;
SELECT * FROM TA_USERS LIMIT 1000000000;
UPDATE TA_USERS SET FCROLE = 'ADMIN' WHERE FCEMAIL LIKE '%';
DELETE FROM audit_log WHERE event_type LIKE '%%';
SELECT id FROM TA_USERS LIMIT 9999; -- table row count declared: 50000
UPDATE TA_USERS SET FCROLE = 'ADMIN' WHERE user_id = user_id;
SELECT id FROM users u JOIN roles r ON 1 = 1;
